#                        _       _             __               
#                       (_)     | |           / _|              
#  _   _ ___  ___ _ __   _ _ __ | |_ ___ _ __| |_ __ _  ___ ___ 
# | | | / __|/ _ \ '__| | | '_ \| __/ _ \ '__|  _/ _` |/ __/ _ \
# | |_| \__ \  __/ |    | | | | | ||  __/ |  | || (_| | (_|  __/
#  \__,_|___/\___|_|    |_|_| |_|\__\___|_|  |_| \__,_|\___\___|
                                                              

"ui.background" = { bg = "background" }
"ui.text" = "white"
"ui.text.inactive" = { fg = "white" }

"ui.gutter" = { bg = "background" }
"ui.linenr" = { fg = "brightblack", bg = "background" }
"ui.linenr.selected" = { fg = "pink", bg = "background", modifiers = ["bold"] }

"ui.selection" = { fg = "white", bg = "pink" }
"ui.selection.primary" = { fg = "white", bg = "pink" }

"ui.menu" = { fg = "white", bg = "background" }
"ui.menu.selected" = { fg = "white", bg = "pink" }
"ui.help" = { fg = "pink", bg = "background" }

"ui.popup.info" = { fg = "pink", bg = "background" } 
# "ui.text.info" = { fg = "pink" }

"ui.cursor" = { fg = "pink", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "pink", modifiers = ["dim"] }

"ui.statusline" = { fg = "white", bg = "pink" }
"ui.statusline.inactive" = { fg = "brightblack", bg = "white" }



#                  _               _     _       _     _ _       _     _   _             
#                 | |             | |   (_)     | |   | (_)     | |   | | (_)            
#  ___ _   _ _ __ | |_ __ ___  __ | |__  _  __ _| |__ | |_  __ _| |__ | |_ _ _ __   __ _ 
# / __| | | | '_ \| __/ _` \ \/ / | '_ \| |/ _` | '_ \| | |/ _` | '_ \| __| | '_ \ / _` |
# \__ \ |_| | | | | || (_| |>  <  | | | | | (_| | | | | | | (_| | | | | |_| | | | | (_| |
# |___/\__, |_| |_|\__\__,_/_/\_\ |_| |_|_|\__, |_| |_|_|_|\__, |_| |_|\__|_|_| |_|\__, |
#       __/ |                               __/ |           __/ |                   __/ |
#      |___/                               |___/           |___/                   |___/ 

"variable" = "red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "yellow"
"string"  = "green"
"variable.other.member" = "green"
"constant.character.escape" = "cyan"
"function" = "blue"
"constructor" = "blue"
"special" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"



#                       _                
#                      | |               
#  _ __ ___   __ _ _ __| | ___   _ _ __  
# | '_ ` _ \ / _` | '__| |/ / | | | '_ \ 
# | | | | | | (_| | |  |   <| |_| | |_) |
# |_| |_| |_|\__,_|_|  |_|\_\\__,_| .__/ 
#                                 | |    
#                                 |_|    

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"



#      _ _  __  __ 
#     | (_)/ _|/ _|
#   __| |_| |_| |_ 
#  / _` | |  _|  _|
# | (_| | | | | |  
#  \__,_|_|_| |_|  

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"                 
                 


#      _ _                             _   _      
#     | (_)                           | | (_)     
#   __| |_  __ _  __ _ _ __   ___  ___| |_ _  ___ 
#  / _` | |/ _` |/ _` | '_ \ / _ \/ __| __| |/ __|
# | (_| | | (_| | (_| | | | | (_) \__ \ |_| | (__ 
#  \__,_|_|\__,_|\__, |_| |_|\___/|___/\__|_|\___|
#                 __/ |                           
#                |___/                            

"diagnostic" = { modifiers = ["underlined"] }
"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"



#              _      _   _       
#             | |    | | | |      
#  _ __   __ _| | ___| |_| |_ ___ 
# | '_ \ / _` | |/ _ \ __| __/ _ \
# | |_) | (_| | |  __/ |_| ||  __/
# | .__/ \__,_|_|\___|\__|\__\___|
# | |                             
# |_|                             

[palette]

background = "#1e1e1e"
pink = "#e11f84"

black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

brightblack = "#666666"
brightblue = "#3b8eea"
brightcyan = "#29b8db"
brightgreen = "#23d18b"
brightmagenta = "#d670d6"
brightred = "#f14c4c"
brightwhite = "#e5e5e5"
brightyellow = "#f5f543"

